project:
  type: book
  output-dir: public

number-depth: 2
filters:
  - pyodide

book:
  title: "Intro to Python for Kids and Teens"
  author: "Xylotl"
  date: "25/04/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Basics"
      chapters:
       - variables.qmd
  appendices:
    - playground.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



