project:
  type: book

number-depth: 2
filters:
  - pyodide

book:
  title: "Intro to Python for Kids and Teens"
  author: "Xylotl"
  date: last-modified 
  date-format: medium
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - part: "Basics"
      chapters:
        - characteristics.qmd
        - variables.qmd
  appendices:
    - playground.qmd

format:
  html:
    theme:
      - cosmo
      - brand

