# Preface {.unnumbered}

This resource is created with the intention of introducing children and teenagers to python, however at an appropriate level without gameyfied coding. This is aimed towards kids with autism, and through relating basic programming concepts to easily recognisable everyday concepts, without dumbing it down. Not all learning styles can be accounted for, however several variations are attempted with the intention that at least one is understandable.

The structure will guide you through basic programming concepts, with demonstrations then the ability for you to type in your own code to demonstrate your understanding of the concepts. This is intended to be guided through with an instructor, to ensure your code is accurate. However there will be an example of a correct answer if you want to teach yourself or are simply stuck. There is also a [playground](playground.qmd) if you want to just try out some code without being restricted to the lessons.

### Covering
* Data types and variables
* Input and print
* Conditional Statements
* Loops
  * While
  * For
* Arranging data types (Lists, arrays and more!)
* Functions
* Modules
* Classes
* Appendices
  * Formatting
  * Environments
  * Library Package Installer



